### ISSUE TITLE
Cannot resize "help" window

### ISSUE THREAD

**Issue by ChenLeiyu** [AY2425S1-CS2103T-T12-4/tp#203]

**Comment by flyingsalsa** [comment]
is this really an issue doe? resizing doesnt make any of the elements any bigger and helps prevent real bugs if users try to resize to a weird aspect ratio that breaks things

**Comment by ChenLeiyu** [comment]
The table is slightly larger than the window so you will need to scroll a bit to view the other commands. My first instinct when using is to expand the window to see all the commands at once for convenience but that is not possible. If implementing this is too much effort or prone to bugs then it is fine.

**Comment by flyingsalsa** [comment]
technically it's just one line, i forgot that the new commands cause the table to extend downwards slightly more lol
