### ISSUE TITLE
[PE-D][Tester A] User guide image not updated

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-4/tp#259]
![Screenshot from 2024-11-08 16-22-50.png](https://raw.githubusercontent.com/AngPengXuan/ped/main/files/9aa9414d-1e64-4868-ba07-a5dc75cd4ab1.png)

Above is found in page 7 of user guide.

User guide image not updated, showing old UI of address book

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: AngPengXuan/ped#1

**Comment by JJtan2002** [comment]
Fixed by #255
