### ISSUE TITLE
[PE-D][Tester C] [Feature] Emails need have a proper domain with either ".net" ".com" or etc

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-4/tp#266]
**Minor**  logic flaw, possible solution is just to include a case to find ".com", ".org", ".net" or other possible domains within the substring. 

Of course, there are thousands of domains names, but based on context of who your audience is, 99.99% of them would have a email ending with .com(as its their personal email).

This does not affect functionality, just being more stricter on email input requirements.

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

<i><video controls><source src="https://raw.githubusercontent.com/saajidshaik02/ped/main/files/be737ef1-2162-4568-b8f8-e59b0a257463.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/saajidshaik02/ped/main/files/be737ef1-2162-4568-b8f8-e59b0a257463.mp4</i>

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: saajidshaik02/ped#3

**Comment by JJtan2002** [comment]
This could be closed as a suggestion.
