### ISSUE TITLE
[PE-D][Tester B] Inconsistency in DG user stories and UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-4/tp#268]
The user stories in the DG mention to find a contact by name and game. However in the UG, it is only possible to find a contact by name and time-range. 

There is an inconsistency in the DG and UG

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: T1duS/ped#3

**Comment by ChenLeiyu** [comment]
"findgame" command added to UG
