### ISSUE TITLE
[PE-D][Tester C] [Feature] "What if game title too long"

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T12-4/tp#271]
Perhaps you can set the contact card to fixed upper width limit and any characters above that limit will be appended with "..." :0

Or use text wrap for css

Highly unlikely, to find titles with such long names (unless you play those japanese games) hence, very low severity

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

![Screenshot 2024-11-08 153134.png](https://raw.githubusercontent.com/saajidshaik02/ped/main/files/bd40c670-f6d2-4c96-841b-27a7b6f60a71.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: saajidshaik02/ped#4

**Comment by JJtan2002** [comment]
Can add this as an enhancement in DG
