### ISSUE TITLE
[PE-D][Tester E] UI does not resize to match number of items

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T12-4/tp#279]
Currently the size of the display grid remains the same regardless of the number of items on display. 

Steps to reproduce: 
1. clear
2. add n/testname1
3. list

![image.png](https://raw.githubusercontent.com/volleyballkickedme/ped/main/files/8405f6de-a60c-4324-8514-d5b5182a3661.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: volleyballkickedme/ped#2

**Comment by flyingsalsa** [comment]
Can't be fixed under feature freeze
